# Tensorflow 101: Introduction to low-level API

*Prequisites*:
1. Sudah menginstal tensorflow
2. Minat dan semangat
3. Sudah dengerin kami presentasi tentang pengantar dari tensorflow bagian pertama


### Cek *dependencies*

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'1.11.0'

*seems okay*

# Simple Computational Graph


Membuat grafik penjumlahan. **ingat: build then running**. Pertama yang perlu dilakukan adalah membuat dahulu *computational graph*nya.

Namun untuk kesempatan pertama ini, kita mencoba dengan menggunakan fungsi ``tf.constant`` untuk membuat konstanta.


### tf.constant
```
tf.constant(
    value,
    dtype=None,
    shape=None,
    name='Const',
    verify_shape=False
)
```


Untuk membuat konstanta. Hasilnya adalah tensor dengan nilai yang sesuai dengan ``dtype`` dan bernilai sama dengan ``value`` dengan ukuran (opsional) dengan ``shape``

[Dokumentasi dalam bentuk kode](https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/python/framework/constant_op.py#L118)

[Dokumentasi dari tf](https://www.tensorflow.org/api_docs/python/tf/constant)

In [70]:
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7])
tensor.__dict__

Tensor("Const_57:0", shape=(7,), dtype=int32)


In [62]:
print(tensor) # Tensor dengan konstanta nilai [1 2 3 4 5 6 7]
print(type(tensor))

Tensor("Const:0", shape=(7,), dtype=int32)
<class 'tensorflow.python.framework.ops.Tensor'>


Dari hasil cetak di atas tidak mengnampilkan nilai karena sebenarnya pada tf yang dibangung ada *computational graph*nya. Objek ``Tensor`` tersebut hanya merepresentasikan model yang sedang dirancang

In [72]:
var_a = tf.constant([1.0,2.0], dtype=tf.float32, name='var_a')
print(var_a)

Tensor("var_a_7:0", shape=(2,), dtype=float32)


Oke, setelah paham dengan ``tf.constant`` maka selanjutnya kita bisa membuat *graph*nya

## Build the graph

In [73]:
a = tf.constant(5.0, dtype=tf.float32)
b = tf.constant(9.0, dtype=tf.float32)
total = a + b # tf bisa langsung dijumlah
print(a)
print(b)
print(total)

Tensor("Const_58:0", shape=(), dtype=float32)
Tensor("Const_59:0", shape=(), dtype=float32)
Tensor("add_43:0", shape=(), dtype=float32)


### Tensorboard

Sebuah fungsi yang mempermudah pengguna untuk melihat graph yang telah dibuat.

Untuk menjalankannya, ketik

``` tensorboard --logdir .```

pada terminal/cmd **setelah menjalankan potongan program dibawah**

In [7]:
writer = tf.summary.FileWriter('.') # Nama berkas dapat diganti, 
# begitu juga dengan shell command-nya
writer.add_graph(tf.get_default_graph())

Buka ```localhost:6006``` (secara *default*) maka akan didapati gambar kurang lebih seperti ini:

![sim_graph](sim_com_gr_tf.PNG "sim graph")


## *Compile! (Run the graph)*

In [50]:
sess = tf.Session()
print(sess.run(total))

14.0


Pada saat dijalankan, semua ``tf.Tensor`` hanya memilki nilai tunggal (satu jenis nilai) meski telah menggunakan fungsi random. Sebagai contoh kita memanggil fungsi ``tf.random_uniform`` yang akan menghasil vektor dengan 5 elemen kemudian menjalakan *session*nya.

In [48]:
vec = tf.random_uniform(shape=(5,))
out1 = vec + 1
out2 = vec + 2
out3 = vec + 3
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2, out3))) # single run

[0.7603297  0.66622686 0.6522037  0.47789836 0.38161469]
[0.91934454 0.8587626  0.54179955 0.6407614  0.15005732]
(array([1.2112677, 1.1283487, 1.3393263, 1.1525744, 1.909684 ],
      dtype=float32), array([2.2112677, 2.1283488, 2.3393264, 2.1525745, 2.909684 ],
      dtype=float32), array([3.2112677, 3.1283488, 3.3393264, 3.1525745, 3.909684 ],
      dtype=float32))


Dari hasil diatas menunjukkan bahwa dalam *single run* nilai yang dihasilkan dari ``tf.random_uniform`` hanya memiliki satu jenis nilai.


**Jadi ini aja?** *ngga*

#### Latihan 1
Kalau sudah paham dengan penggunaan konstanta tadi, coba kerjakan latihan berikut:
1. Buat graph perkalian array/list
2. Apa yang dilakukan oleh potongan script berikut? **Jangan dahulu dijalankan**

```
x = tf.constant([1, 2, 3])
x_sum = tf.reduce_sum(x)
result = x_sum/tf.size(x)
```

3. Jalankan program diatas untuk melihat hasilnya! *feel free*, buat ganti nilainya

In [37]:
#array1 = tf.constant([1, 2, 3])
#array2 = tf.constant([4, 5, 6])
perkalian = array1 * array2

print(sess.run(perkalian))

Tensor("Const_21:0", shape=(3,), dtype=int32)
[ 4 10 18]


In [61]:
# Nomor 3 disini
x = tf.constant([1, 2, 3])
x_sum = tf.reduce_sum(x)
result = x_sum/tf.size(x)

print(x)

Tensor("Const_49:0", shape=(3,), dtype=int32)
Tensor("Sum_11:0", shape=(), dtype=int32)


### *Feeding with tf.placeholder* (Ngasih makan; kurang lebih) 

Ngga cuma dengan konstanta aja, graph yang dirancang juga bisa menerima input menggunakan fungsi ``tf.placeholder``. Fungsi ini mirip dengan membuat fungsi pada python. Keterangannya sebagai berikut:

Sebagai contoh:

In [76]:
# Membut graph perkalian
var_a = tf.placeholder(name='A', dtype=tf.float32)
var_b = tf.placeholder(name='B', dtype=tf.float32)
result = var_a*var_b

Sekarang coba isi dengan nilai. Yang perlu diperhatikan, saat mengisi ``feed_dict``, nilai ``key`` yang ditulis adalah nama dari *placeholder*nya.

In [87]:
print(sess.run(result, feed_dict={var_a: 4.0, var_b: [5.0, 9.0]}))

[20. 36.]


In [13]:
# Cara lain. Cari tahu dahulu nama dari masing-masing placeholder
print(var_a.name)
print(var_b.name)

A:0
B:0


In [14]:
print(sess.run(result, feed_dict={sess.graph.get_tensor_by_name('A:0'): 4, 
                                  sess.graph.get_tensor_by_name('B:0'): 5}))

20.0


In [89]:
# Input array
print(sess.run(result, feed_dict={var_a: [[3, 4, 5],
                                          [1, 2, 3],
                                          [2, 3, 3]], 
                                  var_b: [1, 2, 3]}))

[[ 3.  8. 15.]
 [ 1.  4.  9.]
 [ 2.  6.  9.]]


**Paham?** *sekarang soal lagi*

#### Latihan 2
Fungsi nomor 1 & 2 di latihan sebelumnya dibuat agar dapat menerima input dari *user* menggunakan fungsi ``input()`` bawaan dari python!

In [91]:
# Kerjakan disini!1!11!!!
array11 = tf.placeholder(name = 'array1', dtype = tf.float32)
array22 = tf.placeholder(name = 'array2', dtype = tf.float32)

print(sess.run(perkalian, feed_dict = {array1: [1, 2, 3], array2: [4, 5, 6]}))

[ 4 10 18]


### Datasets

Kalau tadi sudah paham dengan fungsi dari ``tf.placeholder`` untuk melakukan eksperimen, maka ada cara lain yang lebih 'dibenarkan' oleh *tensorflow* untuk melakukan *streaming data* ke graph.

Langkah kerja dari *streaming data* menggunakan `tf.data`:
1. Buat variabel *slices* atau iterator untuk memotong data
2. Panggil iterator ke session
3. Ketika sudah mencapai akhir dari baris, maka akan menghasilkan error. Oleh sebab itu harus menggunakan metode *try-catch-exception*
4. Langkah 2-3 dilakukan dalam perulangan *while* (umumnya)

In [17]:
data_saya = [
    [2, 49,],
    [4, 78,],
    [5, 6,],
    [9, 12,],
]
slices = tf.data.Dataset.from_tensor_slices(data_saya)
next_item = slices.make_one_shot_iterator().get_next()
count =0
while True:
  try:
    print('Iterasi ke-', count)
    print(sess.run(next_item))
    count+=1
  except tf.errors.OutOfRangeError:
    break

Iterasi ke- 0
[ 2 49]
Iterasi ke- 1
[ 4 78]
Iterasi ke- 2
[5 6]
Iterasi ke- 3
[ 9 12]
Iterasi ke- 4


Contoh berikut ini jika dataset bergantung pada suatu *state* atau keadaan. Misal harus menghasilkan nilai random

In [18]:
r = tf.random_normal([10,3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()
count=0
sess.run(iterator.initializer)
while True:
  try:
    count+=1
    print('Iterasi ke-', count)
    print(sess.run(next_row))
  except tf.errors.OutOfRangeError:
    break

Iterasi ke- 1
[-0.5839663  1.6364378 -1.2317228]
Iterasi ke- 2
[0.3168752 2.156057  1.6453125]
Iterasi ke- 3
[-0.57186604  2.1056297   0.21125238]
Iterasi ke- 4
[0.4015604  0.26328003 0.7662576 ]
Iterasi ke- 5
[ 1.7264186 -1.1958507  0.9459681]
Iterasi ke- 6
[-0.566021   -0.6482344  -0.15351574]
Iterasi ke- 7
[-0.73578376  0.94195205 -0.69560534]
Iterasi ke- 8
[ 0.62999207 -0.741986    0.40793163]
Iterasi ke- 9
[-0.3778479  -1.9170401   0.14551489]
Iterasi ke- 10
[ 1.4251328 -1.1331409  0.6267209]
Iterasi ke- 11


**Paham?** *ngga, ayo soal lagi*

#### Latihan 3
Fungsi nomor 2 di latihan 3 sebelumnya dibuat agar menghasilkan nilai dari array ``data_saya``

In [19]:
# Hint: Hanya operasi resultnya saja yang digunakan
data_saya = [
    [2, 49,],
    [4, 78,],
    [5, 6,],
    [9, 12,],
]
slices = tf.data.Dataset.from_tensor_slices(data_saya)
iterator = dataset.make_initializable_iterator()
next_item = iterator.get_next()
next_item_int = tf.cast(next_item, tf.int32)
result = next_item_int/tf.size(next_item)
count =0
sess.run(iterator.initializer)
while True:
  try:
    print('Iterasi ke-', count)
    print(sess.run(next_item))
    print(sess.run(result))
    count+=1
  except tf.errors.OutOfRangeError:
    break

Iterasi ke- 0
[ 2.1765006   0.05930461 -0.12781437]
[ 0.          0.         -0.33333333]
Iterasi ke- 1
[ 0.03758975 -0.15088688  1.0872008 ]
[0.         0.33333333 0.        ]
Iterasi ke- 2
[-1.4449342   0.43607014  0.07112093]
[ 0.          0.33333333 -0.33333333]
Iterasi ke- 3
[ 0.34370634 -1.3137289   0.35764   ]
[-0.33333333  0.          0.33333333]
Iterasi ke- 4
[-1.2142249  -0.21597858 -0.9705483 ]
[0.         0.         0.33333333]
Iterasi ke- 5


### Layers
*Finally, layers! but not in this discussion* 

**sorry!**